AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AI Photo Album Lambda CD
Resources:
  Hw2ApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      OpenApiVersion: "2.0"
      DefinitionUri: AI Photo Search-v1-swagger.yaml
      
  Hw2PhotoBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: 6998hw2
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET,PUT,POST,OPTION
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - Etag
            Id: myCORSRuleId1


  Hw2SearchPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 6998HW2_LF2_example
      Handler: 6998HW2_LF2.py.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambda/6998HW2_LF2.py
      Description: 'Lambda function for Searching Photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::061102422979:role/service-role/6998HW2_LF2-role-ryttgo4l'
      Policies:
        - AmazonLexFullAccess
        - AWSLambdaBasicExecutionRole-b12a639d-25f7-4f58-a632-5364ecfa9856
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: /search
            Method: get
            RestApiId:
              Ref: Hw2ApiGateway
      Environment:
        Variables:
          REGION: us-east-1

  Hw3IndexPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 6998HW2_LF1_example
      Handler: 6998HW2_LF1.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambda/6998HW2_LF1.py
      Description: 'Lambda function for Indexing Photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::061102422979:role/service-role/6998HW2_LF1-role-bwirtl1l'
      Policies:
        - AmazonS3FullAccess
        - AWSLambdaBasicExecutionRole-36b4c9f3-09af-4ac7-8f89-445b6d2c4d70
      Events:
        UploadS3:
          Type: S3
          Properties:
            Bucket:
              Ref: Hw2PhotoBucket
            Events: 's3:ObjectCreated:Put'
      Environment:
        Variables:
          REGION: us-east-1


Outputs:
  BucketName:
    Value:
      Ref: Hw2PhotoBucket
    Description: Hw3 photo bucket