AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AI Photo Album Lambda CD
Resources:
  Api1:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      OpenApiVersion: "3.0"
      DefinitionUri: AI Photo Search-v1-oas30.yaml
      
  Bucket1:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: 6998hw2photo
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - 'GET,PUT,POST'
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - 'Etag'

  6998HW2LF1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambda/6998HW2_LF1.py
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::207598852675:role/service-role/6998HW2_LF1-role-vwcil9ea'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
        Api1:
          Type: Api
          Properties:
            Path: /upload
            Method: PUT
      Layers:
        - >-
          arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-requests:15
        - >-
          arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-aws-requests-auth:7
    
  6998HW2LF2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambda/6998HW2_LF1.py
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::207598852675:role/service-role/6998HW2_LF2-role-yfqnis4x'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
      Layers:
        - >-
          arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-requests:15
        - >-
          arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-aws-requests-auth:7
  