AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AI Photo Album Lambda CD
Resources:
  Hw2ApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      OpenApiVersion: "3.0"
      DefinitionUri: AI Photo Search-v1-oas30.yaml
      
  Hw2PhotoBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: 6998hw2photo
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - 'GET,PUT,POST'
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - 'Etag'



  Hw2SearchPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 6998HW2_LF2_example
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambda/6998HW2_LF2.py
      Description: 'Lambda function for Searching Photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::207598852675:role/service-role/6998HW2_LF2-role-yfqnis4x'
      Policies:
        - AmazonS3FullAccess
        - AmazonTranscribeFullAccess
        - AmazonRekognitionFullAccess
        - AmazonLexFullAccess
        - AWSLambdaBasicExecutionRole-0454e01c-9d97-4fb5-9135-83a3985832c7
        - AWSQuickSightElasticsearchPolicy
        - AWSLambda_FullAccess
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: /search
            Method: get
            RestApiId:
              Ref: Hw2ApiGateway
      Environment:
        Variables:
          REGION: us-east-1

  Hw3IndexPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 6998HW2_LF1_example
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambda/6998HW2_LF1.py
      Description: 'Lambda function for Indexing Photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::207598852675:role/service-role/6998HW2_LF1-role-vwcil9ea'
      Policies:
        - AmazonS3FullAccess
        - AmazonTranscribeFullAccess
        - AmazonRekognitionFullAccess
        - AmazonLexFullAccess
        - AWSLambdaBasicExecutionRole-0454e01c-9d97-4fb5-9135-83a3985832c7
        - AWSQuickSightElasticsearchPolicy
        - AWSLambda_FullAccess
      Events:
        UploadS3:
          Type: S3
          Properties:
            Bucket:
              Ref: Hw2PhotoBucket
            Events: 's3:ObjectCreated:Put'
      Environment:
        Variables:
          REGION: us-east-1


Outputs:
  BucketName:
    Value:
      Ref: Hw2PhotoBucket
    Description: Hw3 photo bucket